### ISSUE TITLE
Html Tags ending up in the /data.php?q=relevéEtudiant endpoint's json response

### ISSUE THREAD

**Issue by Leikoe** [SebL68/Scodoc_Notes#110]
two html tags end up in the json response on the /data endpoint

<img width="918" alt="image" src="https://user-images.githubusercontent.com/44068562/200768934-23eb31a8-f8a0-442d-82b0-2382291a5994.png">

**Comment by SebL68** [comment]
Corrigé https://github.com/SebL68/Scodoc_Notes/commit/ca51ef56dea1fd44b1f9f2d283e75d2c713a0f28
