### ISSUE TITLE
Les heures de pause sont comptées lorsqu'un enseignant entre une journée entière d'absences

### ISSUE THREAD

**Issue by CeIest** [SebL68/Scodoc_Notes#143]
Lorsqu'un enseignant compte une journée entière d'absence d'un coup (dans ce cas : de 10h00 à 17h30) au lieu d'entrées séparées, les heures de pause telles que celle entre 12h00 et 13h30 sont comptées dans les totaux (ce qui pourrait éventuellement affecter les points malus si les absences ne sont pas justifiées)

Cas : [Image](https://i.imgur.com/7lc6iJ6.png), (22 heures au lieu de 23 heures 30)

À moins que cela est intentionnel ?

**Comment by SebL68** [comment]
Bonjour Celest,

(Dans ce qui suit, je parle des cas où les absences sont enregistrées dans Scodoc)

En effet, la passerelle ne prévoit pas les journées entières car d'un IUT, d'un département, d'une formation à l'autre, la pause de midi peut changer. Parfois même au sein d'un même département. C'est pourquoi il n'y a pas d'option pour définir cette durée.

L'idéal est de placer les absences sur les créneaux exactes de l'emplois du temps.

Scodoc propose de définir les heures de formation, mais il faut être sûr que ce soit pour tout le monde pareil.
Pour le moment, il est possible de récupérer les totaux dans Scodoc pour les responsables de formation.
Dans le futur, il y aura une option pour avoir les totaux issus de Scodoc affichés sur la passerelle (à la place de la passerelle qui les calcule).

En espérant que ça réponde à la question :-)
Bonne journée,
Seb

**Comment by SebL68** [comment]
L'option mentionnée est lié à cette issue : https://github.com/SebL68/Scodoc_Notes/issues/134

**Comment by SebL68** [comment]
Résolu lors du dernier commit
