### ISSUE TITLE
Affichage du relevé pdf erroné 

### ISSUE THREAD

**Issue by Piel-M** [SebL68/Scodoc_Notes#154]
Bonjour, je refais cette année une première année de BUT informatique suite à une année blanche, quand je télécharge mon bulletin au format pdf sur la deuxième année, les états des UE finaux sont ceux de l'année précédente. Alors qu'il sont correctement affichés sur la version web.
![Capture d’écran_2024-02-14_12-06-48](https://github.com/SebL68/Scodoc_Notes/assets/64580284/4e91e4d0-8dc8-46f5-a571-9d5edd87deeb)
![Capture d’écran_2024-02-14_12-08-05](https://github.com/SebL68/Scodoc_Notes/assets/64580284/ee97a703-7e8e-4fdd-a36d-096dacce1788)

**Comment by SebL68** [comment]
Bonjour,
Les decisions sur les UE sont différentes des décisions sur les compétences qui sont le regroupement d'une UE du premier semestre et du deuxième semestre (aussi appelé RCUE) et donc l'année.

Lorsque vous aurez passé le deuxième semestre, cette décision sera remplacée.

Si vous souhaitez en parler plus, c'est scodoc qui gère ceci, la passerelle ne fait que transmettre les données. Il faudrait alors aller sur le discord de scodoc.

Bonne journée,
Seb
