### ISSUE TITLE
Compte admin

### ISSUE THREAD

**Issue by SebL68** [SebL68/Scodoc_Notes#7]
Mettre en place un système de comptes admins.

**Comment by SebL68** [comment]
L'idée est de créer trois statuts de comptes : 
1. étudiant,
2. personnel,
3. admin

Chaque compte ayant les privilèges du niveau inférieur.
On pourra utiliser des constantes au début du fichier [/includes/LDAPData.php](url)
Ce fichier étant chargé lorsqu'on a besoin du statut, on pourra tester facilement le niveau de droits.

Exemple :
`<?php
     define("ETUDIANT", 1);

    // [...]

    if(statut >= PERSONNEL){
        // Statut personnel ou admin
    }
?>`

**Comment by dg-68** [comment]
Modification du fichier LDAPData.php.
Le statut ADMINISTRATEUR est attribué sur la base du fichier LDAP/administrateurs.json

**Comment by SebL68** [comment]
On pourrait d'ailleurs mettre des numéros par dizaines, du genre : 
10. étudiant,
20. personnel,
30. admin

On aurait ainsi la liberté de créer des statuts intermédiaire si besoin.

**Comment by SebL68** [comment]
Notes pour plus tard : penser à mettre à jour 
- /html/services/documentation.php 
- /README.md

En fonction des modifications
