### ISSUE TITLE
Impossible de télécharger les relevé de notes

### ISSUE THREAD

**Issue by SitePPP** [SebL68/Scodoc_Notes#94]
Bonjour,
Il est impossible de télécharger les relevé de notes, il semblerait que sem_id soit mal envoyé (sem_id=[object).
Cordialement

**Comment by SitePPP** [comment]
Il semblerait que la variable : ${semestre} ne soit pas mise par défaut sur le trimestre affiché 
(Dans le fichier releve_dut.js)

**Comment by SebL68** [comment]
C'est noté, je regarde ça demain. J'ai également prévu de proposer le téléchargement des relevés pour les BUT.

**Comment by SitePPP** [comment]
Le bug se produit lorsque l’on essaie de télécharger le bulletin de notes mais que l’on a pas cliqué sur un autre trimestre.. la variable ${semestre} n’est pas initialiser par défaut (je suppose), du coup JavaScript met un objet à la place d’un string dans la requêtes vers le php du bulletin de notes

**Comment by SebL68** [comment]
Hum pas moyen de reproduire le problème, est ce que la passerelle est à jour chez toi ?
Sinon vient sur le discord pour en parler, ce sera plus simple : https://discord.gg/FgMNZ4SdD4

PS : je suis en train d'effectuer de gros changement de fond sur la passerelle, je ne recommande pas de faire une mise à jour maitnenant.

**Comment by SebL68** [comment]
Je ferme le ticket car je n'arrive pas à reproduire le problème.
